version: '3.8'
services:

  serverless:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    image: mylambda
    container_name: mylambda
    env_file: .env
    volumes:
      - $HOME/.aws:/root/.aws
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
