service: notify-aws-billing

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ce:GetCostAndUsage
      Resource:
        - '*'

functions:
  notify_aws_billing:
    handler: handler.notify_aws_billing
    timeout: 10
    events:
      - schedule: cron(0 1 ? * MON-FRI *)
    environment:
      WEBHOOK_URL: ${opt:url}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
