service: notify-aws-billing

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}

functions:
  notify_aws_billing:
    handler: handler.notify_aws_billing
    # memorySize: 256
    # timeout: 30s
    events:
      - schedule: cron(0 1 * * ? *)
    environment:
      WEBHOOK_URL: ${opt:url}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
