FROM lambci/lambda:build-python3.8
LABEL maintainer="yudaiogawa"

RUN pip install pipenv

RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash - \
    && yum install -y nodejs-14.15.1 \
    && npm i -g serverless
